### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by stephenbawks** [gozup/serverless-ssm-fetch#7]
Will this work with SSM Parameters that in list format? Would I be able to pass in the list to a attribute, say Subnets for example?

Will this work with specifying wildcards in the parameter name when looking one up?

**Comment by gozup** [comment]
Hello @stephenbawks,

Sorry for the delay. No it won't. 
In my opinion, since subnet are not sensitive data, you could handle them in a share configuration file. That's what I do for most of my serverless project.
And if you still want to use Store Parameters, maybe you can create one param per subnet ?

Best
Emmanuel
